#!/bin/sh

set -e
. /usr/share/debconf/confmodule

if ! test -f /etc/hosts; then
    exit 0
fi

if grep -q rtpg /etc/hosts; then
    exit 0
fi

db_input high rtpg-www/change_host || true
db_go || true
