#!/bin/sh


#TODO: add config ask for this actions

update_hosts()
{
    	echo 127.0.0.1 rtpg rtpg-scgi.localhost >> /etc/hosts
}

if test -f /etc/hosts; then
    grep -q rtpg-scgi /etc/hosts ||	update_hosts
else
	    umask 022
    	update_hosts
fi

#DEBHELPER#
