#!/bin/sh

set -e

. /usr/share/debconf/confmodule

if ! test -f /etc/hosts; then
    exit 0
fi

if grep -q rtpg /etc/hosts; then
    exit 0
fi

db_get rtpg-www/change_host

if test "$RET" = true; then
    umask 022
    echo 127.0.0.1 rtpg rtpg-scgi.localhost >> /etc/hosts
fi

#DEBHELPER#
